### ISSUE TITLE
Kontoverbindungen hinterlegen

### ISSUE THREAD

**Issue by datenbrille** [firegento/verein#10]
Wir brauchen hier die Kontoverbindungen noch.

**Comment by Schrank** [comment]
Wir sollten die Bankverbindung nicht veröffentlichen, dann haben wir ständig Abbuchungen drauf :-/

**Comment by Schrank** [comment]
Darf aber gerne in den vereinsöffentlichen Bereich.

**Comment by drlrdsen** [comment]
Von welchen Bankverbindungen redet ihr?

**Comment by Schrank** [comment]
Das Vereinskonto, damit man auch via Dauerauftrag/Überweisung seinen Mitgliedsbeitrag bezahlen kann.

**Comment by drlrdsen** [comment]
Aber wie bekommst du denn Abbuchungen auf das Konto, wenn du die Kontodaten kennst?

**Comment by Schrank** [comment]
Man bestellt irgendwo, bezahlt mit Lastschrift und trägt unsere Kontodaten ein :)

**Comment by riconeitzel** [comment]
Wer macht denn SOWAS?! :D

**Comment by drlrdsen** [comment]
Finde ich das ein wenig abwegig? Wie auch immer ihr meint. Aber hört auf, mir wegen sowas ständig E-Mail-Notifikationen zu schicken :P

**Comment by Schrank** [comment]
Das ist dein Knopf :package: 
![bildschirmfoto 2015-10-13 um 14 03 55](https://cloud.githubusercontent.com/assets/379680/10454208/4870502c-71b3-11e5-9748-0443fd6cd842.png)

**Comment by riconeitzel** [comment]
:+1:

**Comment by drlrdsen** [comment]
Vielen Dank.
